// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuperCom.Infrastructure.Data;

#nullable disable

namespace SuperCom.Infrastructure.Data.Migrations
{
    [DbContext(typeof(SuperComDbContext))]
    partial class SuperComDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SuperCom.Core.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Urgent"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bug"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Feature"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Improvement"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Documentation"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Research"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Testing"
                        },
                        new
                        {
                            Id = 8,
                            Name = "DevOps"
                        });
                });

            modelBuilder.Entity("SuperCom.Core.Entities.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<bool>("ReminderSent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("UserFullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("UserTelephone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            CreatedAt = new DateTime(2025, 12, 20, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Users can submit the login form with an empty password field. Add client-side and server-side validation.",
                            DueDate = new DateTime(2026, 1, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsCompleted = false,
                            Priority = 2,
                            ReminderSent = false,
                            RowVersion = new byte[0],
                            Title = "Fix login page validation bug",
                            UserEmail = "dana.cohen@example.com",
                            UserFullName = "Dana Cohen",
                            UserTelephone = "050-1234567"
                        },
                        new
                        {
                            Id = 101,
                            CreatedAt = new DateTime(2025, 12, 28, 9, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Cover all CRUD operations and edge cases. Target 90% code coverage for the service layer.",
                            DueDate = new DateTime(2026, 1, 12, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsCompleted = false,
                            Priority = 1,
                            ReminderSent = false,
                            RowVersion = new byte[0],
                            Title = "Write unit tests for TaskService",
                            UserEmail = "yossi.levi@example.com",
                            UserFullName = "Yossi Levi",
                            UserTelephone = "052-9876543"
                        },
                        new
                        {
                            Id = 102,
                            CreatedAt = new DateTime(2026, 1, 2, 11, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Swagger docs are outdated after the latest endpoint changes. Update all request/response examples.",
                            DueDate = new DateTime(2026, 1, 18, 12, 0, 0, 0, DateTimeKind.Utc),
                            IsCompleted = false,
                            Priority = 0,
                            ReminderSent = false,
                            RowVersion = new byte[0],
                            Title = "Update API documentation",
                            UserEmail = "noa.shapira@example.com",
                            UserFullName = "Noa Shapira",
                            UserTelephone = "054-5551234"
                        },
                        new
                        {
                            Id = 103,
                            CreatedAt = new DateTime(2026, 1, 8, 7, 45, 0, 0, DateTimeKind.Utc),
                            Description = "The tasks list endpoint takes over 3 seconds for large datasets. Profile and optimize the SQL queries.",
                            DueDate = new DateTime(2026, 1, 22, 9, 0, 0, 0, DateTimeKind.Utc),
                            IsCompleted = false,
                            Priority = 3,
                            ReminderSent = false,
                            RowVersion = new byte[0],
                            Title = "Investigate slow database queries",
                            UserEmail = "amit.peretz@example.com",
                            UserFullName = "Amit Peretz",
                            UserTelephone = "053-7778899"
                        },
                        new
                        {
                            Id = 104,
                            CreatedAt = new DateTime(2026, 1, 10, 13, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Configure GitHub Actions to build, test, and deploy on every push to main branch.",
                            DueDate = new DateTime(2026, 1, 28, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsCompleted = false,
                            Priority = 2,
                            ReminderSent = false,
                            RowVersion = new byte[0],
                            Title = "Set up CI/CD pipeline",
                            UserEmail = "shira.bd@example.com",
                            UserFullName = "Shira Ben-David",
                            UserTelephone = "050-3334455"
                        },
                        new
                        {
                            Id = 105,
                            CreatedAt = new DateTime(2026, 2, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Send email reminders 24 hours before a task's due date using the ReminderService.",
                            DueDate = new DateTime(2026, 3, 3, 9, 0, 0, 0, DateTimeKind.Utc),
                            IsCompleted = false,
                            Priority = 2,
                            ReminderSent = false,
                            RowVersion = new byte[0],
                            Title = "Implement task reminder notifications",
                            UserEmail = "tomer.az@example.com",
                            UserFullName = "Tomer Azulay",
                            UserTelephone = "052-1112233"
                        },
                        new
                        {
                            Id = 106,
                            CreatedAt = new DateTime(2026, 2, 18, 14, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Implement a theme toggle in the UI. Persist the user's preference in localStorage.",
                            DueDate = new DateTime(2026, 3, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            IsCompleted = false,
                            Priority = 0,
                            ReminderSent = false,
                            RowVersion = new byte[0],
                            Title = "Add dark mode support to frontend",
                            UserEmail = "maya.gold@example.com",
                            UserFullName = "Maya Goldstein",
                            UserTelephone = "054-6667788"
                        },
                        new
                        {
                            Id = 107,
                            CreatedAt = new DateTime(2026, 2, 20, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Build a dashboard showing task counts by priority, overdue tasks, and completion trends.",
                            DueDate = new DateTime(2026, 3, 15, 11, 0, 0, 0, DateTimeKind.Utc),
                            IsCompleted = false,
                            Priority = 1,
                            ReminderSent = false,
                            RowVersion = new byte[0],
                            Title = "Create user dashboard with task statistics",
                            UserEmail = "eyal.m@example.com",
                            UserFullName = "Eyal Mizrachi",
                            UserTelephone = "050-8889900"
                        },
                        new
                        {
                            Id = 108,
                            CreatedAt = new DateTime(2026, 2, 19, 9, 15, 0, 0, DateTimeKind.Utc),
                            Description = "Evaluate and plan migration from SQL Server to PostgreSQL for cost reduction in production.",
                            DueDate = new DateTime(2026, 3, 22, 15, 0, 0, 0, DateTimeKind.Utc),
                            IsCompleted = false,
                            Priority = 3,
                            ReminderSent = false,
                            RowVersion = new byte[0],
                            Title = "Migrate database to PostgreSQL",
                            UserEmail = "lior.katz@example.com",
                            UserFullName = "Lior Katz",
                            UserTelephone = "053-2223344"
                        },
                        new
                        {
                            Id = 109,
                            CreatedAt = new DateTime(2026, 2, 21, 16, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Allow users to export filtered task lists as CSV files from the frontend.",
                            DueDate = new DateTime(2026, 3, 28, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsCompleted = false,
                            Priority = 1,
                            ReminderSent = false,
                            RowVersion = new byte[0],
                            Title = "Add export tasks to CSV feature",
                            UserEmail = "rotem.h@example.com",
                            UserFullName = "Rotem Haim",
                            UserTelephone = "052-4445566"
                        });
                });

            modelBuilder.Entity("SuperCom.Core.Entities.TaskTag", b =>
                {
                    b.Property<int>("TaskItemId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("TaskItemId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("TaskTags");

                    b.HasData(
                        new
                        {
                            TaskItemId = 100,
                            TagId = 2
                        },
                        new
                        {
                            TaskItemId = 100,
                            TagId = 1
                        },
                        new
                        {
                            TaskItemId = 101,
                            TagId = 7
                        },
                        new
                        {
                            TaskItemId = 102,
                            TagId = 5
                        },
                        new
                        {
                            TaskItemId = 103,
                            TagId = 2
                        },
                        new
                        {
                            TaskItemId = 103,
                            TagId = 6
                        },
                        new
                        {
                            TaskItemId = 104,
                            TagId = 8
                        },
                        new
                        {
                            TaskItemId = 105,
                            TagId = 3
                        },
                        new
                        {
                            TaskItemId = 105,
                            TagId = 4
                        },
                        new
                        {
                            TaskItemId = 106,
                            TagId = 3
                        },
                        new
                        {
                            TaskItemId = 107,
                            TagId = 3
                        },
                        new
                        {
                            TaskItemId = 107,
                            TagId = 4
                        },
                        new
                        {
                            TaskItemId = 108,
                            TagId = 8
                        },
                        new
                        {
                            TaskItemId = 108,
                            TagId = 6
                        },
                        new
                        {
                            TaskItemId = 109,
                            TagId = 3
                        });
                });

            modelBuilder.Entity("SuperCom.Core.Entities.TaskTag", b =>
                {
                    b.HasOne("SuperCom.Core.Entities.Tag", "Tag")
                        .WithMany("TaskTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SuperCom.Core.Entities.TaskItem", "TaskItem")
                        .WithMany("TaskTags")
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("SuperCom.Core.Entities.Tag", b =>
                {
                    b.Navigation("TaskTags");
                });

            modelBuilder.Entity("SuperCom.Core.Entities.TaskItem", b =>
                {
                    b.Navigation("TaskTags");
                });
#pragma warning restore 612, 618
        }
    }
}
